version: '3.1'

services:

  api:
    build: .
    ports:
     - "5000:5000"
    environment:
      ENV: DEV
    restart: always
    volumes:
      - ./app:/app
    links:
    - db
    - mongo

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes: 
      - ./db/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  myadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links: 
      - db
    ports:
      - 8082:80

  mongo:
    image: mongo
    restart: always
    volumes: 
      - ./db/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    links:
      - mongo
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example